# Generated by Django 6.1.1 on 2026-09-29 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numero_documento', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro'), ('PREFIERO_NO_DECIRLO', 'Prefiero no decirlo')], max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('AUTOR', 'Autor')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento de Identidad'), ('PASSPORT', 'Pasaporte'), ('CEDULA', 'Cedula de Ciudadanía'), ('OTRO', 'Otro')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_Editorial', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('nombre_editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_barras', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'En mantenimiento')], max_length=20)),
                ('ubicacion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('numero_documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='autor', serialize=False, to='app_catalogo.persona')),
                ('nacionalidad', models.CharField(blank=True, max_length=45, null=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('numero_documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to='app_catalogo.persona')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45, unique=True)),
                ('grado_escolar', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('edicion', models.CharField(max_length=45)),
                ('ISBN', models.CharField(max_length=45, unique=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_catalogo.editorial')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_catalogo.libro')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_catalogo.tema')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='app_catalogo.autor')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_catalogo.autor'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Prestamo', models.DateField()),
                ('Fecha_Devolucion', models.DateField()),
                ('Observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app_catalogo.libro')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app_catalogo.estudiante')),
            ],
        ),
    ]
